/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/AppLink.vue')['default']
    README: typeof import('./../../components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowRoot: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/internals/ShadowRoot.vue')['default']
    ValaxyAddons: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyAddons.vue')['default']
    ValaxyApp: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyApp.vue')['default']
    ValaxyCopyright: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyCopyright.vue')['default']
    ValaxyDecrypt: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyDecrypt.vue')['default']
    ValaxyDynamicComponent: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyDynamicComponent.vue')['default']
    ValaxyFootnoteTooltip: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyFootnoteTooltip.vue')['default']
    ValaxyGalleryDecrypt: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyGalleryDecrypt.vue')['default']
    ValaxyHamburger: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyHamburger.vue')['default']
    ValaxyLogo: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyLogo.vue')['default']
    ValaxyMain: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyMain.vue')['default']
    ValaxyMd: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyMd.vue')['default']
    ValaxyMermaid: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/builtin/ValaxyMermaid.vue')['default']
    ValaxyOverlay: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyOverlay.vue')['default']
    ValaxyPagination: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxyPagination.vue')['default']
    ValaxySvgLogo: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/ValaxySvgLogo.vue')['default']
    ValaxyTranslate: typeof import('./../../../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/components/builtin/ValaxyTranslate.vue')['default']
  }
}
