/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/_drafts/a-story-about-coc-22': RouteRecordInfo<'/_drafts/a-story-about-coc-22', '/_drafts/a-story-about-coc-22', Record<never, never>, Record<never, never>>,
    '/_drafts/abandon/add-web-notification-for-blog': RouteRecordInfo<'/_drafts/abandon/add-web-notification-for-blog', '/_drafts/abandon/add-web-notification-for-blog', Record<never, never>, Record<never, never>>,
    '/_drafts/go-far-away': RouteRecordInfo<'/_drafts/go-far-away', '/_drafts/go-far-away', Record<never, never>, Record<never, never>>,
    '/_drafts/how-to-migrate-element-plus-var': RouteRecordInfo<'/_drafts/how-to-migrate-element-plus-var', '/_drafts/how-to-migrate-element-plus-var', Record<never, never>, Record<never, never>>,
    '/_drafts/how-to-write-a-bezier-curve-sketch-pad': RouteRecordInfo<'/_drafts/how-to-write-a-bezier-curve-sketch-pad', '/_drafts/how-to-write-a-bezier-curve-sketch-pad', Record<never, never>, Record<never, never>>,
    '/_drafts/i-and-game': RouteRecordInfo<'/_drafts/i-and-game', '/_drafts/i-and-game', Record<never, never>, Record<never, never>>,
    '/_drafts/imitate-2048-game': RouteRecordInfo<'/_drafts/imitate-2048-game', '/_drafts/imitate-2048-game', Record<never, never>, Record<never, never>>,
    '/_drafts/make-ak-ui': RouteRecordInfo<'/_drafts/make-ak-ui', '/_drafts/make-ak-ui', Record<never, never>, Record<never, never>>,
    '/_drafts/minecraft-survival-diary': RouteRecordInfo<'/_drafts/minecraft-survival-diary', '/_drafts/minecraft-survival-diary', Record<never, never>, Record<never, never>>,
    '/_drafts/my-first-internship-and-work': RouteRecordInfo<'/_drafts/my-first-internship-and-work', '/_drafts/my-first-internship-and-work', Record<never, never>, Record<never, never>>,
    '/_drafts/my-next-blog': RouteRecordInfo<'/_drafts/my-next-blog', '/_drafts/my-next-blog', Record<never, never>, Record<never, never>>,
    '/_drafts/my-youth-is-over': RouteRecordInfo<'/_drafts/my-youth-is-over', '/_drafts/my-youth-is-over', Record<never, never>, Record<never, never>>,
    '/_drafts/old/happy-fool-day': RouteRecordInfo<'/_drafts/old/happy-fool-day', '/_drafts/old/happy-fool-day', Record<never, never>, Record<never, never>>,
    '/_drafts/old/README': RouteRecordInfo<'/_drafts/old/README', '/_drafts/old/README', Record<never, never>, Record<never, never>>,
    '/_drafts/re0-to-be-a-vtuber': RouteRecordInfo<'/_drafts/re0-to-be-a-vtuber', '/_drafts/re0-to-be-a-vtuber', Record<never, never>, Record<never, never>>,
    '/_drafts/README': RouteRecordInfo<'/_drafts/README', '/_drafts/README', Record<never, never>, Record<never, never>>,
    '/_drafts/today-let-us-cook': RouteRecordInfo<'/_drafts/today-let-us-cook', '/_drafts/today-let-us-cook', Record<never, never>, Record<never, never>>,
    '/_drafts/what-i-do-for-element-plus-style-system': RouteRecordInfo<'/_drafts/what-i-do-for-element-plus-style-system', '/_drafts/what-i-do-for-element-plus-style-system', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/air-conditioner-room/': RouteRecordInfo<'/air-conditioner-room/', '/air-conditioner-room', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/music/': RouteRecordInfo<'/music/', '/music', Record<never, never>, Record<never, never>>,
    '/play/': RouteRecordInfo<'/play/', '/play', Record<never, never>, Record<never, never>>,
    '/posts/12K-20K面试题': RouteRecordInfo<'/posts/12K-20K面试题', '/posts/12K-20K面试题', Record<never, never>, Record<never, never>>,
    '/posts/aijiu-info': RouteRecordInfo<'/posts/aijiu-info', '/posts/aijiu-info', Record<never, never>, Record<never, never>>,
    '/posts/Alertmanage最详细的配置文件解释': RouteRecordInfo<'/posts/Alertmanage最详细的配置文件解释', '/posts/Alertmanage最详细的配置文件解释', Record<never, never>, Record<never, never>>,
    '/posts/Centos-7.9-使用kubeadm安装kubernetes-1.25.0': RouteRecordInfo<'/posts/Centos-7.9-使用kubeadm安装kubernetes-1.25.0', '/posts/Centos-7/9-使用kubeadm安装kubernetes-1/25/0', Record<never, never>, Record<never, never>>,
    '/posts/Centos7编译安装SHC并加密脚本文件': RouteRecordInfo<'/posts/Centos7编译安装SHC并加密脚本文件', '/posts/Centos7编译安装SHC并加密脚本文件', Record<never, never>, Record<never, never>>,
    '/posts/Centos8.1搭建LAMP(YUM)': RouteRecordInfo<'/posts/Centos8.1搭建LAMP(YUM)', '/posts/Centos8/1搭建LAMP(YUM)', Record<never, never>, Record<never, never>>,
    '/posts/clear-k8s-node-tmp': RouteRecordInfo<'/posts/clear-k8s-node-tmp', '/posts/clear-k8s-node-tmp', Record<never, never>, Record<never, never>>,
    '/posts/Consul+Registrator+Nginx实现容器服务自动发现': RouteRecordInfo<'/posts/Consul+Registrator+Nginx实现容器服务自动发现', '/posts/Consul+Registrator+Nginx实现容器服务自动发现', Record<never, never>, Record<never, never>>,
    '/posts/Consul使用中文手册': RouteRecordInfo<'/posts/Consul使用中文手册', '/posts/Consul使用中文手册', Record<never, never>, Record<never, never>>,
    '/posts/containerd-clean': RouteRecordInfo<'/posts/containerd-clean', '/posts/containerd-clean', Record<never, never>, Record<never, never>>,
    '/posts/DHCP动态分配IP地址（Linux）': RouteRecordInfo<'/posts/DHCP动态分配IP地址（Linux）', '/posts/DHCP动态分配IP地址（Linux）', Record<never, never>, Record<never, never>>,
    '/posts/docker-version-update': RouteRecordInfo<'/posts/docker-version-update', '/posts/docker-version-update', Record<never, never>, Record<never, never>>,
    '/posts/Docker+K8s实践指南': RouteRecordInfo<'/posts/Docker+K8s实践指南', '/posts/Docker+K8s实践指南', Record<never, never>, Record<never, never>>,
    '/posts/Dockerfile小实验': RouteRecordInfo<'/posts/Dockerfile小实验', '/posts/Dockerfile小实验', Record<never, never>, Record<never, never>>,
    '/posts/Docker基本四种网络模型': RouteRecordInfo<'/posts/Docker基本四种网络模型', '/posts/Docker基本四种网络模型', Record<never, never>, Record<never, never>>,
    '/posts/Docker搭建Nginx日志高级监控-基于Loki-+-Promtail-+-Grafana': RouteRecordInfo<'/posts/Docker搭建Nginx日志高级监控-基于Loki-+-Promtail-+-Grafana', '/posts/Docker搭建Nginx日志高级监控-基于Loki-+-Promtail-+-Grafana', Record<never, never>, Record<never, never>>,
    '/posts/Docker的daemon.json配置详解': RouteRecordInfo<'/posts/Docker的daemon.json配置详解', '/posts/Docker的daemon/json配置详解', Record<never, never>, Record<never, never>>,
    '/posts/Docker的引入': RouteRecordInfo<'/posts/Docker的引入', '/posts/Docker的引入', Record<never, never>, Record<never, never>>,
    '/posts/edit-coredns-config-hosts': RouteRecordInfo<'/posts/edit-coredns-config-hosts', '/posts/edit-coredns-config-hosts', Record<never, never>, Record<never, never>>,
    '/posts/ELK-Nginx日志分析及绘图': RouteRecordInfo<'/posts/ELK-Nginx日志分析及绘图', '/posts/ELK-Nginx日志分析及绘图', Record<never, never>, Record<never, never>>,
    '/posts/ELK-部署文档': RouteRecordInfo<'/posts/ELK-部署文档', '/posts/ELK-部署文档', Record<never, never>, Record<never, never>>,
    '/posts/ELK+Redis+Grafana监控分析Nginx生产日志终极版': RouteRecordInfo<'/posts/ELK+Redis+Grafana监控分析Nginx生产日志终极版', '/posts/ELK+Redis+Grafana监控分析Nginx生产日志终极版', Record<never, never>, Record<never, never>>,
    '/posts/ELK日志收集系统概括': RouteRecordInfo<'/posts/ELK日志收集系统概括', '/posts/ELK日志收集系统概括', Record<never, never>, Record<never, never>>,
    '/posts/ES-Elasticsearch数据库备份恢复脚本': RouteRecordInfo<'/posts/ES-Elasticsearch数据库备份恢复脚本', '/posts/ES-Elasticsearch数据库备份恢复脚本', Record<never, never>, Record<never, never>>,
    '/posts/GItlab设计与部署': RouteRecordInfo<'/posts/GItlab设计与部署', '/posts/GItlab设计与部署', Record<never, never>, Record<never, never>>,
    '/posts/Git命令集合~': RouteRecordInfo<'/posts/Git命令集合~', '/posts/Git命令集合~', Record<never, never>, Record<never, never>>,
    '/posts/GlusterFS分布式文件系统群集': RouteRecordInfo<'/posts/GlusterFS分布式文件系统群集', '/posts/GlusterFS分布式文件系统群集', Record<never, never>, Record<never, never>>,
    '/posts/Go语言入门-安装踩坑': RouteRecordInfo<'/posts/Go语言入门-安装踩坑', '/posts/Go语言入门-安装踩坑', Record<never, never>, Record<never, never>>,
    '/posts/Grafana-Tencent-Exporter-Image-Send-Wechat': RouteRecordInfo<'/posts/Grafana-Tencent-Exporter-Image-Send-Wechat', '/posts/Grafana-Tencent-Exporter-Image-Send-Wechat', Record<never, never>, Record<never, never>>,
    '/posts/Grafana为Dashboard添加独立权限控制': RouteRecordInfo<'/posts/Grafana为Dashboard添加独立权限控制', '/posts/Grafana为Dashboard添加独立权限控制', Record<never, never>, Record<never, never>>,
    '/posts/Harbor部署总结': RouteRecordInfo<'/posts/Harbor部署总结', '/posts/Harbor部署总结', Record<never, never>, Record<never, never>>,
    '/posts/HTTPS': RouteRecordInfo<'/posts/HTTPS', '/posts/HTTPS', Record<never, never>, Record<never, never>>,
    '/posts/install-mongodb-replicas-cluster': RouteRecordInfo<'/posts/install-mongodb-replicas-cluster', '/posts/install-mongodb-replicas-cluster', Record<never, never>, Record<never, never>>,
    '/posts/install-nacos': RouteRecordInfo<'/posts/install-nacos', '/posts/install-nacos', Record<never, never>, Record<never, never>>,
    '/posts/Iptables防火墙机制': RouteRecordInfo<'/posts/Iptables防火墙机制', '/posts/Iptables防火墙机制', Record<never, never>, Record<never, never>>,
    '/posts/Jenkins（CA-CI）部署': RouteRecordInfo<'/posts/Jenkins（CA-CI）部署', '/posts/Jenkins（CA-CI）部署', Record<never, never>, Record<never, never>>,
    '/posts/Jenkins汉化并修改插件源为国内源': RouteRecordInfo<'/posts/Jenkins汉化并修改插件源为国内源', '/posts/Jenkins汉化并修改插件源为国内源', Record<never, never>, Record<never, never>>,
    '/posts/Jumpserver安装使用': RouteRecordInfo<'/posts/Jumpserver安装使用', '/posts/Jumpserver安装使用', Record<never, never>, Record<never, never>>,
    '/posts/k8s-kube-prometheus-probe-blackbox-exporter': RouteRecordInfo<'/posts/k8s-kube-prometheus-probe-blackbox-exporter', '/posts/k8s-kube-prometheus-probe-blackbox-exporter', Record<never, never>, Record<never, never>>,
    '/posts/k8s-zhengshuxuqi': RouteRecordInfo<'/posts/k8s-zhengshuxuqi', '/posts/k8s-zhengshuxuqi', Record<never, never>, Record<never, never>>,
    '/posts/k8s-zhengshuxuqian-other': RouteRecordInfo<'/posts/k8s-zhengshuxuqian-other', '/posts/k8s-zhengshuxuqian-other', Record<never, never>, Record<never, never>>,
    '/posts/K8S(kubernetes)实践认知': RouteRecordInfo<'/posts/K8S(kubernetes)实践认知', '/posts/K8S(kubernetes)实践认知', Record<never, never>, Record<never, never>>,
    '/posts/k8spacket-grafana-view': RouteRecordInfo<'/posts/k8spacket-grafana-view', '/posts/k8spacket-grafana-view', Record<never, never>, Record<never, never>>,
    '/posts/k8s删除pv一直处于terminating': RouteRecordInfo<'/posts/k8s删除pv一直处于terminating', '/posts/k8s删除pv一直处于terminating', Record<never, never>, Record<never, never>>,
    '/posts/Kafka运维笔记': RouteRecordInfo<'/posts/Kafka运维笔记', '/posts/Kafka运维笔记', Record<never, never>, Record<never, never>>,
    '/posts/kubernetes-coredns添加自定义DNS解析记录': RouteRecordInfo<'/posts/kubernetes-coredns添加自定义DNS解析记录', '/posts/kubernetes-coredns添加自定义DNS解析记录', Record<never, never>, Record<never, never>>,
    '/posts/Kubernetes-Operator配置自动发现新增ServiceMonitor的NameSpace': RouteRecordInfo<'/posts/Kubernetes-Operator配置自动发现新增ServiceMonitor的NameSpace', '/posts/Kubernetes-Operator配置自动发现新增ServiceMonitor的NameSpace', Record<never, never>, Record<never, never>>,
    '/posts/Kubernetes-使用Nginx-Ingress实现蓝绿发布-金丝雀发布-AB测试': RouteRecordInfo<'/posts/Kubernetes-使用Nginx-Ingress实现蓝绿发布-金丝雀发布-AB测试', '/posts/Kubernetes-使用Nginx-Ingress实现蓝绿发布-金丝雀发布-AB测试', Record<never, never>, Record<never, never>>,
    '/posts/kubernetes中部署kube-prometheus项目解决ControllerManager与Scheduler无法监控问题': RouteRecordInfo<'/posts/kubernetes中部署kube-prometheus项目解决ControllerManager与Scheduler无法监控问题', '/posts/kubernetes中部署kube-prometheus项目解决ControllerManager与Scheduler无法监控问题', Record<never, never>, Record<never, never>>,
    '/posts/Kubernetes使用NFS作为动态存储（提供下载YAML）': RouteRecordInfo<'/posts/Kubernetes使用NFS作为动态存储（提供下载YAML）', '/posts/Kubernetes使用NFS作为动态存储（提供下载YAML）', Record<never, never>, Record<never, never>>,
    '/posts/Kubernetes排障指南': RouteRecordInfo<'/posts/Kubernetes排障指南', '/posts/Kubernetes排障指南', Record<never, never>, Record<never, never>>,
    '/posts/KVM-未完': RouteRecordInfo<'/posts/KVM-未完', '/posts/KVM-未完', Record<never, never>, Record<never, never>>,
    '/posts/Linux-find-命令详解': RouteRecordInfo<'/posts/Linux-find-命令详解', '/posts/Linux-find-命令详解', Record<never, never>, Record<never, never>>,
    '/posts/linux-syslog-ttl': RouteRecordInfo<'/posts/linux-syslog-ttl', '/posts/linux-syslog-ttl', Record<never, never>, Record<never, never>>,
    '/posts/Linux-双网卡绑定': RouteRecordInfo<'/posts/Linux-双网卡绑定', '/posts/Linux-双网卡绑定', Record<never, never>, Record<never, never>>,
    '/posts/linux-性能、统计、分析、优化，常用的命令': RouteRecordInfo<'/posts/linux-性能、统计、分析、优化，常用的命令', '/posts/linux-性能、统计、分析、优化，常用的命令', Record<never, never>, Record<never, never>>,
    '/posts/linux压力测试工具': RouteRecordInfo<'/posts/linux压力测试工具', '/posts/linux压力测试工具', Record<never, never>, Record<never, never>>,
    '/posts/Linux指令入门指令': RouteRecordInfo<'/posts/Linux指令入门指令', '/posts/Linux指令入门指令', Record<never, never>, Record<never, never>>,
    '/posts/Linux环境初始化': RouteRecordInfo<'/posts/Linux环境初始化', '/posts/Linux环境初始化', Record<never, never>, Record<never, never>>,
    '/posts/LInux系统介绍': RouteRecordInfo<'/posts/LInux系统介绍', '/posts/LInux系统介绍', Record<never, never>, Record<never, never>>,
    '/posts/Linux系统负载总结': RouteRecordInfo<'/posts/Linux系统负载总结', '/posts/Linux系统负载总结', Record<never, never>, Record<never, never>>,
    '/posts/LNMP(YUM)': RouteRecordInfo<'/posts/LNMP(YUM)', '/posts/LNMP(YUM)', Record<never, never>, Record<never, never>>,
    '/posts/LVM添加硬盘并扩容至已有分区': RouteRecordInfo<'/posts/LVM添加硬盘并扩容至已有分区', '/posts/LVM添加硬盘并扩容至已有分区', Record<never, never>, Record<never, never>>,
    '/posts/mac-dev-django-mysql': RouteRecordInfo<'/posts/mac-dev-django-mysql', '/posts/mac-dev-django-mysql', Record<never, never>, Record<never, never>>,
    '/posts/MarkDown语法解析': RouteRecordInfo<'/posts/MarkDown语法解析', '/posts/MarkDown语法解析', Record<never, never>, Record<never, never>>,
    '/posts/Mysql+Keepalived-双主热备高可用图文配置详解': RouteRecordInfo<'/posts/Mysql+Keepalived-双主热备高可用图文配置详解', '/posts/Mysql+Keepalived-双主热备高可用图文配置详解', Record<never, never>, Record<never, never>>,
    '/posts/MYSQL命令行输入密码警告问题解决方案': RouteRecordInfo<'/posts/MYSQL命令行输入密码警告问题解决方案', '/posts/MYSQL命令行输入密码警告问题解决方案', Record<never, never>, Record<never, never>>,
    '/posts/MySQL高可用晋升': RouteRecordInfo<'/posts/MySQL高可用晋升', '/posts/MySQL高可用晋升', Record<never, never>, Record<never, never>>,
    '/posts/nginx-updata': RouteRecordInfo<'/posts/nginx-updata', '/posts/nginx-updata', Record<never, never>, Record<never, never>>,
    '/posts/Nginx反向代理负载均衡': RouteRecordInfo<'/posts/Nginx反向代理负载均衡', '/posts/Nginx反向代理负载均衡', Record<never, never>, Record<never, never>>,
    '/posts/node-exporter扩展用法-shell自定义exporter监控': RouteRecordInfo<'/posts/node-exporter扩展用法-shell自定义exporter监控', '/posts/node-exporter扩展用法-shell自定义exporter监控', Record<never, never>, Record<never, never>>,
    '/posts/ocp-route-etcpasswd': RouteRecordInfo<'/posts/ocp-route-etcpasswd', '/posts/ocp-route-etcpasswd', Record<never, never>, Record<never, never>>,
    '/posts/Prometheus-Operator配置自动发现新增ServiceMonitor的NameSpace': RouteRecordInfo<'/posts/Prometheus-Operator配置自动发现新增ServiceMonitor的NameSpace', '/posts/Prometheus-Operator配置自动发现新增ServiceMonitor的NameSpace', Record<never, never>, Record<never, never>>,
    '/posts/Prometheus+Grafana全方位监控系统': RouteRecordInfo<'/posts/Prometheus+Grafana全方位监控系统', '/posts/Prometheus+Grafana全方位监控系统', Record<never, never>, Record<never, never>>,
    '/posts/PrometheusAlert-一个基于Prometheus_alertmanager的全家桶告警项目': RouteRecordInfo<'/posts/PrometheusAlert-一个基于Prometheus_alertmanager的全家桶告警项目', '/posts/PrometheusAlert-一个基于Prometheus_alertmanager的全家桶告警项目', Record<never, never>, Record<never, never>>,
    '/posts/PXE+Kickstart批量装机': RouteRecordInfo<'/posts/PXE+Kickstart批量装机', '/posts/PXE+Kickstart批量装机', Record<never, never>, Record<never, never>>,
    '/posts/Redis-5.x知识体系梳理': RouteRecordInfo<'/posts/Redis-5.x知识体系梳理', '/posts/Redis-5/x知识体系梳理', Record<never, never>, Record<never, never>>,
    '/posts/Registrator+Consul+Consul-template+HaProxy实现动态修改Haproty配置文件': RouteRecordInfo<'/posts/Registrator+Consul+Consul-template+HaProxy实现动态修改Haproty配置文件', '/posts/Registrator+Consul+Consul-template+HaProxy实现动态修改Haproty配置文件', Record<never, never>, Record<never, never>>,
    '/posts/Sersync-lsync实时同步': RouteRecordInfo<'/posts/Sersync-lsync实时同步', '/posts/Sersync-lsync实时同步', Record<never, never>, Record<never, never>>,
    '/posts/solr-cloud-install': RouteRecordInfo<'/posts/solr-cloud-install', '/posts/solr-cloud-install', Record<never, never>, Record<never, never>>,
    '/posts/solr-to-es': RouteRecordInfo<'/posts/solr-to-es', '/posts/solr-to-es', Record<never, never>, Record<never, never>>,
    '/posts/SSH服务初识': RouteRecordInfo<'/posts/SSH服务初识', '/posts/SSH服务初识', Record<never, never>, Record<never, never>>,
    '/posts/su-cai-jie-xi-jiaocheng': RouteRecordInfo<'/posts/su-cai-jie-xi-jiaocheng', '/posts/su-cai-jie-xi-jiaocheng', Record<never, never>, Record<never, never>>,
    '/posts/Telegraf+InfluxDB+Grafana+Docker搭建服务器监控平台': RouteRecordInfo<'/posts/Telegraf+InfluxDB+Grafana+Docker搭建服务器监控平台', '/posts/Telegraf+InfluxDB+Grafana+Docker搭建服务器监控平台', Record<never, never>, Record<never, never>>,
    '/posts/Tomcat认知梳理': RouteRecordInfo<'/posts/Tomcat认知梳理', '/posts/Tomcat认知梳理', Record<never, never>, Record<never, never>>,
    '/posts/Typecho博客更改邮件发送模板': RouteRecordInfo<'/posts/Typecho博客更改邮件发送模板', '/posts/Typecho博客更改邮件发送模板', Record<never, never>, Record<never, never>>,
    '/posts/vue-build-change-env': RouteRecordInfo<'/posts/vue-build-change-env', '/posts/vue-build-change-env', Record<never, never>, Record<never, never>>,
    '/posts/yijing64': RouteRecordInfo<'/posts/yijing64', '/posts/yijing64', Record<never, never>, Record<never, never>>,
    '/posts/中小型企业架构演变': RouteRecordInfo<'/posts/中小型企业架构演变', '/posts/中小型企业架构演变', Record<never, never>, Record<never, never>>,
    '/posts/什么是-istio？': RouteRecordInfo<'/posts/什么是-istio？', '/posts/什么是-istio？', Record<never, never>, Record<never, never>>,
    '/posts/你真的掌握-LVS、Nginx-及-HAProxy-的工作原理吗？': RouteRecordInfo<'/posts/你真的掌握-LVS、Nginx-及-HAProxy-的工作原理吗？', '/posts/你真的掌握-LVS、Nginx-及-HAProxy-的工作原理吗？', Record<never, never>, Record<never, never>>,
    '/posts/使用-Docker-自建-Bitwarden-密码管理服务器': RouteRecordInfo<'/posts/使用-Docker-自建-Bitwarden-密码管理服务器', '/posts/使用-Docker-自建-Bitwarden-密码管理服务器', Record<never, never>, Record<never, never>>,
    '/posts/使用PHP自制一个图片API接口': RouteRecordInfo<'/posts/使用PHP自制一个图片API接口', '/posts/使用PHP自制一个图片API接口', Record<never, never>, Record<never, never>>,
    '/posts/分享10个可免费使用的网站CDN加速服务': RouteRecordInfo<'/posts/分享10个可免费使用的网站CDN加速服务', '/posts/分享10个可免费使用的网站CDN加速服务', Record<never, never>, Record<never, never>>,
    '/posts/初识Zabbix4.0~': RouteRecordInfo<'/posts/初识Zabbix4.0~', '/posts/初识Zabbix4/0~', Record<never, never>, Record<never, never>>,
    '/posts/各大搜索引擎-User-Agent': RouteRecordInfo<'/posts/各大搜索引擎-User-Agent', '/posts/各大搜索引擎-User-Agent', Record<never, never>, Record<never, never>>,
    '/posts/在k8s中搭建有状态应用Nacos集群': RouteRecordInfo<'/posts/在k8s中搭建有状态应用Nacos集群', '/posts/在k8s中搭建有状态应用Nacos集群', Record<never, never>, Record<never, never>>,
    '/posts/如何选择最佳的-Kubernetes-集群自动伸缩策略-': RouteRecordInfo<'/posts/如何选择最佳的-Kubernetes-集群自动伸缩策略-', '/posts/如何选择最佳的-Kubernetes-集群自动伸缩策略-', Record<never, never>, Record<never, never>>,
    '/posts/简述文件系统共享网络服务NFS': RouteRecordInfo<'/posts/简述文件系统共享网络服务NFS', '/posts/简述文件系统共享网络服务NFS', Record<never, never>, Record<never, never>>,
    '/posts/腾讯云对象存储COSCMD工具安装配置与使用命令详解': RouteRecordInfo<'/posts/腾讯云对象存储COSCMD工具安装配置与使用命令详解', '/posts/腾讯云对象存储COSCMD工具安装配置与使用命令详解', Record<never, never>, Record<never, never>>,
    '/posts/记一次源码编译安装LAMP（附源码包）': RouteRecordInfo<'/posts/记一次源码编译安装LAMP（附源码包）', '/posts/记一次源码编译安装LAMP（附源码包）', Record<never, never>, Record<never, never>>,
    '/posts/轻量级日志分析新秀Loki': RouteRecordInfo<'/posts/轻量级日志分析新秀Loki', '/posts/轻量级日志分析新秀Loki', Record<never, never>, Record<never, never>>,
    '/posts/这些百度搜索小技巧，让你的搜索高效无广告': RouteRecordInfo<'/posts/这些百度搜索小技巧，让你的搜索高效无广告', '/posts/这些百度搜索小技巧，让你的搜索高效无广告', Record<never, never>, Record<never, never>>,
    '/posts/镜像批量迁移工具skopeo从docker-registry到harbor': RouteRecordInfo<'/posts/镜像批量迁移工具skopeo从docker-registry到harbor', '/posts/镜像批量迁移工具skopeo从docker-registry到harbor', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/slides/': RouteRecordInfo<'/slides/', '/slides', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/_drafts/a-story-about-coc-22.md': {
      routes: '/_drafts/a-story-about-coc-22'
      views: never
    }
    'pages/_drafts/abandon/add-web-notification-for-blog.md': {
      routes: '/_drafts/abandon/add-web-notification-for-blog'
      views: never
    }
    'pages/_drafts/go-far-away.md': {
      routes: '/_drafts/go-far-away'
      views: never
    }
    'pages/_drafts/how-to-migrate-element-plus-var.md': {
      routes: '/_drafts/how-to-migrate-element-plus-var'
      views: never
    }
    'pages/_drafts/how-to-write-a-bezier-curve-sketch-pad.md': {
      routes: '/_drafts/how-to-write-a-bezier-curve-sketch-pad'
      views: never
    }
    'pages/_drafts/i-and-game.md': {
      routes: '/_drafts/i-and-game'
      views: never
    }
    'pages/_drafts/imitate-2048-game.md': {
      routes: '/_drafts/imitate-2048-game'
      views: never
    }
    'pages/_drafts/make-ak-ui.md': {
      routes: '/_drafts/make-ak-ui'
      views: never
    }
    'pages/_drafts/minecraft-survival-diary.md': {
      routes: '/_drafts/minecraft-survival-diary'
      views: never
    }
    'pages/_drafts/my-first-internship-and-work.md': {
      routes: '/_drafts/my-first-internship-and-work'
      views: never
    }
    'pages/_drafts/my-next-blog.md': {
      routes: '/_drafts/my-next-blog'
      views: never
    }
    'pages/_drafts/my-youth-is-over.md': {
      routes: '/_drafts/my-youth-is-over'
      views: never
    }
    'pages/_drafts/old/happy-fool-day.md': {
      routes: '/_drafts/old/happy-fool-day'
      views: never
    }
    'pages/_drafts/old/README.md': {
      routes: '/_drafts/old/README'
      views: never
    }
    'pages/_drafts/re0-to-be-a-vtuber.md': {
      routes: '/_drafts/re0-to-be-a-vtuber'
      views: never
    }
    'pages/_drafts/README.md': {
      routes: '/_drafts/README'
      views: never
    }
    'pages/_drafts/today-let-us-cook.md': {
      routes: '/_drafts/today-let-us-cook'
      views: never
    }
    'pages/_drafts/what-i-do-for-element-plus-style-system.md': {
      routes: '/_drafts/what-i-do-for-element-plus-style-system'
      views: never
    }
    '../../Library/pnpm/global/5/.pnpm/valaxy@0.26.3_@babel+parser@7.28.3_@types+markdown-it@14.1.2_@types+node@24.3.0_@vue+co_95c8cb987400823905f2245ef1446c56/node_modules/valaxy/client/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'pages/404.md': {
      routes: '/404'
      views: never
    }
    'pages/about/index.md': {
      routes: '/about/'
      views: never
    }
    'pages/about/site.md': {
      routes: '/about/site'
      views: never
    }
    'pages/air-conditioner-room/index.md': {
      routes: '/air-conditioner-room/'
      views: never
    }
    'pages/archives/index.md': {
      routes: '/archives/'
      views: never
    }
    'pages/categories/index.md': {
      routes: '/categories/'
      views: never
    }
    'pages/girls/index.md': {
      routes: '/girls/'
      views: never
    }
    'pages/links/index.md': {
      routes: '/links/'
      views: never
    }
    'pages/music/index.md': {
      routes: '/music/'
      views: never
    }
    'pages/play/index.md': {
      routes: '/play/'
      views: never
    }
    'pages/posts/12K-20K面试题.md': {
      routes: '/posts/12K-20K面试题'
      views: never
    }
    'pages/posts/aijiu-info.md': {
      routes: '/posts/aijiu-info'
      views: never
    }
    'pages/posts/Alertmanage最详细的配置文件解释.md': {
      routes: '/posts/Alertmanage最详细的配置文件解释'
      views: never
    }
    'pages/posts/Centos-7.9-使用kubeadm安装kubernetes-1.25.0.md': {
      routes: '/posts/Centos-7.9-使用kubeadm安装kubernetes-1.25.0'
      views: never
    }
    'pages/posts/Centos7编译安装SHC并加密脚本文件.md': {
      routes: '/posts/Centos7编译安装SHC并加密脚本文件'
      views: never
    }
    'pages/posts/Centos8.1搭建LAMP(YUM).md': {
      routes: '/posts/Centos8.1搭建LAMP(YUM)'
      views: never
    }
    'pages/posts/clear-k8s-node-tmp.md': {
      routes: '/posts/clear-k8s-node-tmp'
      views: never
    }
    'pages/posts/Consul+Registrator+Nginx实现容器服务自动发现.md': {
      routes: '/posts/Consul+Registrator+Nginx实现容器服务自动发现'
      views: never
    }
    'pages/posts/Consul使用中文手册.md': {
      routes: '/posts/Consul使用中文手册'
      views: never
    }
    'pages/posts/containerd-clean.md': {
      routes: '/posts/containerd-clean'
      views: never
    }
    'pages/posts/DHCP动态分配IP地址（Linux）.md': {
      routes: '/posts/DHCP动态分配IP地址（Linux）'
      views: never
    }
    'pages/posts/docker-version-update.md': {
      routes: '/posts/docker-version-update'
      views: never
    }
    'pages/posts/Docker+K8s实践指南.md': {
      routes: '/posts/Docker+K8s实践指南'
      views: never
    }
    'pages/posts/Dockerfile小实验.md': {
      routes: '/posts/Dockerfile小实验'
      views: never
    }
    'pages/posts/Docker基本四种网络模型.md': {
      routes: '/posts/Docker基本四种网络模型'
      views: never
    }
    'pages/posts/Docker搭建Nginx日志高级监控-基于Loki-+-Promtail-+-Grafana.md': {
      routes: '/posts/Docker搭建Nginx日志高级监控-基于Loki-+-Promtail-+-Grafana'
      views: never
    }
    'pages/posts/Docker的daemon.json配置详解.md': {
      routes: '/posts/Docker的daemon.json配置详解'
      views: never
    }
    'pages/posts/Docker的引入.md': {
      routes: '/posts/Docker的引入'
      views: never
    }
    'pages/posts/edit-coredns-config-hosts.md': {
      routes: '/posts/edit-coredns-config-hosts'
      views: never
    }
    'pages/posts/ELK-Nginx日志分析及绘图.md': {
      routes: '/posts/ELK-Nginx日志分析及绘图'
      views: never
    }
    'pages/posts/ELK-部署文档.md': {
      routes: '/posts/ELK-部署文档'
      views: never
    }
    'pages/posts/ELK+Redis+Grafana监控分析Nginx生产日志终极版.md': {
      routes: '/posts/ELK+Redis+Grafana监控分析Nginx生产日志终极版'
      views: never
    }
    'pages/posts/ELK日志收集系统概括.md': {
      routes: '/posts/ELK日志收集系统概括'
      views: never
    }
    'pages/posts/ES-Elasticsearch数据库备份恢复脚本.md': {
      routes: '/posts/ES-Elasticsearch数据库备份恢复脚本'
      views: never
    }
    'pages/posts/GItlab设计与部署.md': {
      routes: '/posts/GItlab设计与部署'
      views: never
    }
    'pages/posts/Git命令集合~.md': {
      routes: '/posts/Git命令集合~'
      views: never
    }
    'pages/posts/GlusterFS分布式文件系统群集.md': {
      routes: '/posts/GlusterFS分布式文件系统群集'
      views: never
    }
    'pages/posts/Go语言入门-安装踩坑.md': {
      routes: '/posts/Go语言入门-安装踩坑'
      views: never
    }
    'pages/posts/Grafana-Tencent-Exporter-Image-Send-Wechat.md': {
      routes: '/posts/Grafana-Tencent-Exporter-Image-Send-Wechat'
      views: never
    }
    'pages/posts/Grafana为Dashboard添加独立权限控制.md': {
      routes: '/posts/Grafana为Dashboard添加独立权限控制'
      views: never
    }
    'pages/posts/Harbor部署总结.md': {
      routes: '/posts/Harbor部署总结'
      views: never
    }
    'pages/posts/HTTPS.md': {
      routes: '/posts/HTTPS'
      views: never
    }
    'pages/posts/install-mongodb-replicas-cluster.md': {
      routes: '/posts/install-mongodb-replicas-cluster'
      views: never
    }
    'pages/posts/install-nacos.md': {
      routes: '/posts/install-nacos'
      views: never
    }
    'pages/posts/Iptables防火墙机制.md': {
      routes: '/posts/Iptables防火墙机制'
      views: never
    }
    'pages/posts/Jenkins（CA-CI）部署.md': {
      routes: '/posts/Jenkins（CA-CI）部署'
      views: never
    }
    'pages/posts/Jenkins汉化并修改插件源为国内源.md': {
      routes: '/posts/Jenkins汉化并修改插件源为国内源'
      views: never
    }
    'pages/posts/Jumpserver安装使用.md': {
      routes: '/posts/Jumpserver安装使用'
      views: never
    }
    'pages/posts/k8s-kube-prometheus-probe-blackbox-exporter.md': {
      routes: '/posts/k8s-kube-prometheus-probe-blackbox-exporter'
      views: never
    }
    'pages/posts/k8s-zhengshuxuqi.md': {
      routes: '/posts/k8s-zhengshuxuqi'
      views: never
    }
    'pages/posts/k8s-zhengshuxuqian-other.md': {
      routes: '/posts/k8s-zhengshuxuqian-other'
      views: never
    }
    'pages/posts/K8S(kubernetes)实践认知.md': {
      routes: '/posts/K8S(kubernetes)实践认知'
      views: never
    }
    'pages/posts/k8spacket-grafana-view.md': {
      routes: '/posts/k8spacket-grafana-view'
      views: never
    }
    'pages/posts/k8s删除pv一直处于terminating.md': {
      routes: '/posts/k8s删除pv一直处于terminating'
      views: never
    }
    'pages/posts/Kafka运维笔记.md': {
      routes: '/posts/Kafka运维笔记'
      views: never
    }
    'pages/posts/kubernetes-coredns添加自定义DNS解析记录.md': {
      routes: '/posts/kubernetes-coredns添加自定义DNS解析记录'
      views: never
    }
    'pages/posts/Kubernetes-Operator配置自动发现新增ServiceMonitor的NameSpace.md': {
      routes: '/posts/Kubernetes-Operator配置自动发现新增ServiceMonitor的NameSpace'
      views: never
    }
    'pages/posts/Kubernetes-使用Nginx-Ingress实现蓝绿发布-金丝雀发布-AB测试.md': {
      routes: '/posts/Kubernetes-使用Nginx-Ingress实现蓝绿发布-金丝雀发布-AB测试'
      views: never
    }
    'pages/posts/kubernetes中部署kube-prometheus项目解决ControllerManager与Scheduler无法监控问题.md': {
      routes: '/posts/kubernetes中部署kube-prometheus项目解决ControllerManager与Scheduler无法监控问题'
      views: never
    }
    'pages/posts/Kubernetes使用NFS作为动态存储（提供下载YAML）.md': {
      routes: '/posts/Kubernetes使用NFS作为动态存储（提供下载YAML）'
      views: never
    }
    'pages/posts/Kubernetes排障指南.md': {
      routes: '/posts/Kubernetes排障指南'
      views: never
    }
    'pages/posts/KVM-未完.md': {
      routes: '/posts/KVM-未完'
      views: never
    }
    'pages/posts/Linux-find-命令详解.md': {
      routes: '/posts/Linux-find-命令详解'
      views: never
    }
    'pages/posts/linux-syslog-ttl.md': {
      routes: '/posts/linux-syslog-ttl'
      views: never
    }
    'pages/posts/Linux-双网卡绑定.md': {
      routes: '/posts/Linux-双网卡绑定'
      views: never
    }
    'pages/posts/linux-性能、统计、分析、优化，常用的命令.md': {
      routes: '/posts/linux-性能、统计、分析、优化，常用的命令'
      views: never
    }
    'pages/posts/linux压力测试工具.md': {
      routes: '/posts/linux压力测试工具'
      views: never
    }
    'pages/posts/Linux指令入门指令.md': {
      routes: '/posts/Linux指令入门指令'
      views: never
    }
    'pages/posts/Linux环境初始化.md': {
      routes: '/posts/Linux环境初始化'
      views: never
    }
    'pages/posts/LInux系统介绍.md': {
      routes: '/posts/LInux系统介绍'
      views: never
    }
    'pages/posts/Linux系统负载总结.md': {
      routes: '/posts/Linux系统负载总结'
      views: never
    }
    'pages/posts/LNMP(YUM).md': {
      routes: '/posts/LNMP(YUM)'
      views: never
    }
    'pages/posts/LVM添加硬盘并扩容至已有分区.md': {
      routes: '/posts/LVM添加硬盘并扩容至已有分区'
      views: never
    }
    'pages/posts/mac-dev-django-mysql.md': {
      routes: '/posts/mac-dev-django-mysql'
      views: never
    }
    'pages/posts/MarkDown语法解析.md': {
      routes: '/posts/MarkDown语法解析'
      views: never
    }
    'pages/posts/Mysql+Keepalived-双主热备高可用图文配置详解.md': {
      routes: '/posts/Mysql+Keepalived-双主热备高可用图文配置详解'
      views: never
    }
    'pages/posts/MYSQL命令行输入密码警告问题解决方案.md': {
      routes: '/posts/MYSQL命令行输入密码警告问题解决方案'
      views: never
    }
    'pages/posts/MySQL高可用晋升.md': {
      routes: '/posts/MySQL高可用晋升'
      views: never
    }
    'pages/posts/nginx-updata.md': {
      routes: '/posts/nginx-updata'
      views: never
    }
    'pages/posts/Nginx反向代理负载均衡.md': {
      routes: '/posts/Nginx反向代理负载均衡'
      views: never
    }
    'pages/posts/node-exporter扩展用法-shell自定义exporter监控.md': {
      routes: '/posts/node-exporter扩展用法-shell自定义exporter监控'
      views: never
    }
    'pages/posts/ocp-route-etcpasswd.md': {
      routes: '/posts/ocp-route-etcpasswd'
      views: never
    }
    'pages/posts/Prometheus-Operator配置自动发现新增ServiceMonitor的NameSpace.md': {
      routes: '/posts/Prometheus-Operator配置自动发现新增ServiceMonitor的NameSpace'
      views: never
    }
    'pages/posts/Prometheus+Grafana全方位监控系统.md': {
      routes: '/posts/Prometheus+Grafana全方位监控系统'
      views: never
    }
    'pages/posts/PrometheusAlert-一个基于Prometheus_alertmanager的全家桶告警项目.md': {
      routes: '/posts/PrometheusAlert-一个基于Prometheus_alertmanager的全家桶告警项目'
      views: never
    }
    'pages/posts/PXE+Kickstart批量装机.md': {
      routes: '/posts/PXE+Kickstart批量装机'
      views: never
    }
    'pages/posts/Redis-5.x知识体系梳理.md': {
      routes: '/posts/Redis-5.x知识体系梳理'
      views: never
    }
    'pages/posts/Registrator+Consul+Consul-template+HaProxy实现动态修改Haproty配置文件.md': {
      routes: '/posts/Registrator+Consul+Consul-template+HaProxy实现动态修改Haproty配置文件'
      views: never
    }
    'pages/posts/Sersync-lsync实时同步.md': {
      routes: '/posts/Sersync-lsync实时同步'
      views: never
    }
    'pages/posts/solr-cloud-install.md': {
      routes: '/posts/solr-cloud-install'
      views: never
    }
    'pages/posts/solr-to-es.md': {
      routes: '/posts/solr-to-es'
      views: never
    }
    'pages/posts/SSH服务初识.md': {
      routes: '/posts/SSH服务初识'
      views: never
    }
    'pages/posts/su-cai-jie-xi-jiaocheng.md': {
      routes: '/posts/su-cai-jie-xi-jiaocheng'
      views: never
    }
    'pages/posts/Telegraf+InfluxDB+Grafana+Docker搭建服务器监控平台.md': {
      routes: '/posts/Telegraf+InfluxDB+Grafana+Docker搭建服务器监控平台'
      views: never
    }
    'pages/posts/Tomcat认知梳理.md': {
      routes: '/posts/Tomcat认知梳理'
      views: never
    }
    'pages/posts/Typecho博客更改邮件发送模板.md': {
      routes: '/posts/Typecho博客更改邮件发送模板'
      views: never
    }
    'pages/posts/vue-build-change-env.md': {
      routes: '/posts/vue-build-change-env'
      views: never
    }
    'pages/posts/yijing64.md': {
      routes: '/posts/yijing64'
      views: never
    }
    'pages/posts/中小型企业架构演变.md': {
      routes: '/posts/中小型企业架构演变'
      views: never
    }
    'pages/posts/什么是-istio？.md': {
      routes: '/posts/什么是-istio？'
      views: never
    }
    'pages/posts/你真的掌握-LVS、Nginx-及-HAProxy-的工作原理吗？.md': {
      routes: '/posts/你真的掌握-LVS、Nginx-及-HAProxy-的工作原理吗？'
      views: never
    }
    'pages/posts/使用-Docker-自建-Bitwarden-密码管理服务器.md': {
      routes: '/posts/使用-Docker-自建-Bitwarden-密码管理服务器'
      views: never
    }
    'pages/posts/使用PHP自制一个图片API接口.md': {
      routes: '/posts/使用PHP自制一个图片API接口'
      views: never
    }
    'pages/posts/分享10个可免费使用的网站CDN加速服务.md': {
      routes: '/posts/分享10个可免费使用的网站CDN加速服务'
      views: never
    }
    'pages/posts/初识Zabbix4.0~.md': {
      routes: '/posts/初识Zabbix4.0~'
      views: never
    }
    'pages/posts/各大搜索引擎-User-Agent.md': {
      routes: '/posts/各大搜索引擎-User-Agent'
      views: never
    }
    'pages/posts/在k8s中搭建有状态应用Nacos集群.md': {
      routes: '/posts/在k8s中搭建有状态应用Nacos集群'
      views: never
    }
    'pages/posts/如何选择最佳的-Kubernetes-集群自动伸缩策略-.md': {
      routes: '/posts/如何选择最佳的-Kubernetes-集群自动伸缩策略-'
      views: never
    }
    'pages/posts/简述文件系统共享网络服务NFS.md': {
      routes: '/posts/简述文件系统共享网络服务NFS'
      views: never
    }
    'pages/posts/腾讯云对象存储COSCMD工具安装配置与使用命令详解.md': {
      routes: '/posts/腾讯云对象存储COSCMD工具安装配置与使用命令详解'
      views: never
    }
    'pages/posts/记一次源码编译安装LAMP（附源码包）.md': {
      routes: '/posts/记一次源码编译安装LAMP（附源码包）'
      views: never
    }
    'pages/posts/轻量级日志分析新秀Loki.md': {
      routes: '/posts/轻量级日志分析新秀Loki'
      views: never
    }
    'pages/posts/这些百度搜索小技巧，让你的搜索高效无广告.md': {
      routes: '/posts/这些百度搜索小技巧，让你的搜索高效无广告'
      views: never
    }
    'pages/posts/镜像批量迁移工具skopeo从docker-registry到harbor.md': {
      routes: '/posts/镜像批量迁移工具skopeo从docker-registry到harbor'
      views: never
    }
    'pages/projects/index.md': {
      routes: '/projects/'
      views: never
    }
    'pages/README.md': {
      routes: '/README'
      views: never
    }
    'pages/slides/index.md': {
      routes: '/slides/'
      views: never
    }
    'pages/tags/index.md': {
      routes: '/tags/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
